import type { Metadata } from "next";
import { avenir } from "./fonts"; 
import "./globals.css";

export const metadata: Metadata = {
  title: "Guidelines",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${avenir.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
