import type { Metadata } from "next";
import { avenir } from "./fonts"; 
import "./globals.css";
import { Sidebar } from "./components/sidebar";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Guidelines",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${avenir.variable} antialiased`}>
        <div className="flex">
          <Sidebar />
          <main className="flex-1 p-8">{children}</main>
        </div>
         <Footer />
      </body>
    </html>
  );
}
